[package]
name = "window"
version = "0.1.0"
authors = ["kumusan <ryogi0200@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.23.0"
env_logger = "0.7"
